language: go

os:
  - linux
  - osx

go:
  - 1.7
  - 1.8

services:
  - docker
env:
  global:
    - CONTROLLER_IMAGE_NAME=bitnami/kubeless-controller
    - CONTROLLER_IMAGE=${CONTROLLER_IMAGE_NAME}:${TRAVIS_TAG:-build-$TRAVIS_BUILD_ID}
    - CGO_ENABLED=0

before_install:
  - set -e

install:
  - go get github.com/mitchellh/gox github.com/golang/lint/golint
  - >-
    wget -O $GOPATH/bin/kubecfg
    https://github.com/ksonnet/kubecfg/releases/download/v0.2.0/kubecfg-$(go env GOOS)-$(go env GOARCH)
  - chmod +x $GOPATH/bin/kubecfg
  - git clone --depth=1 https://github.com/ksonnet/ksonnet-lib.git
  - export KUBECFG_JPATH=$PWD/ksonnet-lib

script:
  - make test
  - make validation
  - make binary
  - |
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      make controller-image CONTROLLER_IMAGE=$CONTROLLER_IMAGE
    fi
  - make kubeless.yaml

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == linux && \
          "$TRAVIS_BRANCH" == master && \
          "$TRAVIS_PULL_REQUEST" == false && \
          "$TRAVIS_GO_VERSION" =~ '^1\.8\.' ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" index.docker.io
      docker push ${CONTROLLER_IMAGE}
    fi

before_deploy:
  - make binary-cross
  - cd bundles && for d in kubeless_*; do zip -r9 $d.zip $d/; done

deploy:
  provider: releases
  api_key:
    secure: ratV3LtnNO9x5u0bjFz3EMO+qs65k0OIDJOKqBXrWEuwhUZov51gdt0757Znbl4rm57bptiFt9QVMrzoAC/IBLgQ39uo4vXBoRbthxCYrui4Zml2dMz0xlx+hohq/WAOvCdYfFjxeleNWomm1anOxS73iQ3UUPtUofYqcysmpqzzmGuYSYPUC5Ecsv9Tg1y87kPtsc25lj7ba3MTxdvoQcuDAYB9FqJ75fgKU2NxvROf+G7YNJ9z48slzlODQDsBIHrTCGVrBRedjuazILz6+Fhc1ypNL6L9N6DqrpRIK9rd5KOhJPk4pUXfKIHKX/vfuPBGDMWpM/yxPhbn6WoV0S0QjY7ynmVut8TiTJyVHZxwKDRbgl/omdL6RBsKyHkipy2TNir+kfnmxX7PCDkPIsUGmFsjKBRTIFVhbzs6XPMHXXt5IdOOn8YV0CLg2GgG8DtJ5cikz3H7vHuBXMZH4ZobfNObQIqxblCpspzvrnbGOsqD5XNNW+IN3SWe3YsW3hc9/d/xR3o+Gypkhtrno9B/9pQkF+b5VUd7lhPOvXjMcUyNMVMTjlETG3HMhUiXMMbsBqVumF2+8Qi/qWzR8PEN4bzfNdfQWWVpwRpNzeKL+iK/+Vjx7gjSshVE6EmITYk34NO3ef8D2IT6VzIlbOoxVtxlr6NPJkBRhVbtIKY=
  file_glob: true
  file:
    - kubeless.yaml
    - bundles/kubeless_*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: kubeless/kubeless
    go: 1.8
    os: linux
    condition: $CGO_ENABLED = 0
