apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
   kubeless: controller
  namespace: kubeless
  name: controller
  namespace: kubeless
spec:
  replicas: 1
  selector:
    matchLabels:
     kubeless: controller
  template:
    metadata:
      labels:
        kubeless: controller
    spec:
      containers:
      - name: controller
        image: bitnami/kubeless-controller:0.0.12
        imagePullPolicy: IfNotPresent
