apiVersion: v1
kind: Service
metadata:
  labels:
    kubeless: controller
  name: controller
  namespace: kubeless
spec:
  ports:
  - name: controller-port
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    kubeless: controller
  sessionAffinity: None
  type: ClusterIP
