apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kubeless
spec:
  serviceName: "broker"
  replicas: 1
  template:
    metadata:
      labels:
        kubeless: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: broker
        image: bitnami/kafka@sha256:0b7c8b790546ddb9dcd7e8ff4d50f030fc496176238f36789537620bb13fb54c
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: broker.kubeless
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper.kubeless:2181
        ports:
        - containerPort: 9092
        resources: {}
        volumeMounts:
        - name: datadir
          mountPath: /opt/bitnami/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
