apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
   controller: zookeeper-controller
  namespace: kubeless
  name: zookeeper-controller
  namespace: kubeless
spec:
  replicas: 1
  selector:
    matchLabels:
     controller: zookeeper-controller
  template:
    metadata:
      labels:
        controller: zookeeper-controller
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper@sha256:0bbf6503e45fc7d5236513987702b0533d2c777144dfd5022feed9ad89dc6318
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          protocol: TCP
        resources: {}
