apiVersion: v1
kind: Service
metadata:
  labels:
    controller: zookeeper-controller
  name: zookeeper
  namespace: kubeless
spec:
  ports:
  - name: zookeeper-port
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    controller: zookeeper-controller
